### ISSUE TITLE
Bundled npm removes previously installed packages on install

### ISSUE THREAD

**Issue by iyegoroff** [nojaf/fable-docker#1]
npm@5.6.0 bundled with node@9.4.0 has a known issue:
https://github.com/npm/npm/issues/16794
https://github.com/npm/npm/issues/17379

Consider upgrading to latest npm@6.4.1 or switching node version to 8.12.0 or 10.10.0.

**Comment by nojaf** [comment]
Hi @iyegoroff , thanks for bringing this to my attention.
I'm actually working on a next version for this Docker image.
There I'm installing node 10.x, see [Dockerfile](https://github.com/nojaf/fable-docker/blob/remove-mono/Dockerfile).

In the next version I'm planning on not installing mono anymore, since paket now works on .NETCore.
But paket is still in early stages.

**Comment by shinelp100** [comment]
Is there an official reply standard
